### ISSUE TITLE
Crashes when player enters lobby

### ISSUE THREAD

**Issue by shockwaves** [Arcana/node-dota2#390]
```
15 Dec 17:12:49 - Received create/flip/shuffle/kick/launch/leave response {"result":1}
{"result":1}
/var/www/node/node-dota2-latest/node_modules/bytebuffer/dist/bytebuffer-node.js:346
            throw TypeError("Illegal buffer");
            ^

TypeError: Illegal buffer
    at Function.module.exports.ByteBuffer.wrap (/var/www/node/node-dota2-latest/node_modules/bytebuffer/dist/bytebuffer-node.js:346:19)
    at Function.Message.decode (/var/www/node/node-dota2-latest/node_modules/protobufjs/dist/protobuf.js:2930:84)
    at Dota2Client.handleSubscribedType (/var/www/node/node-dota2-latest/handlers/cache.js:43:51)
    at /var/www/node/node-dota2-latest/handlers/cache.js:109:34
    at Array.forEach (native)
    at Dota2Client.onUpdateMultiple (/var/www/node/node-dota2-latest/handlers/cache.js:108:32)
    at SteamGameCoordinator.fromGC (/var/www/node/node-dota2-latest/index.js:58:38)
    at emitThree (events.js:116:13)
    at SteamGameCoordinator.emit (events.js:194:7)
    at SteamGameCoordinator.handlers.(anonymous function) (/var/www/node/node-dota2-latest/node_modules/steam/lib/handlers/game_coordinator/index.js:107:10)

```

**Comment by Crazy-Duck** [comment]
Can you post the steps to reproduce your error?

**Comment by shockwaves** [comment]
1. install node-dota2
	- `git clone https://github.com/Arcana/node-dota2.git`
	- `npm i steam; npm i`
2. go to path `examples`
	- rename `config.js.example` to `config.js`
	- put my credentials, set `config.steamguard` to empty
	- create empty file `sentry` in same directory
3. change `example.js`
	- uncomment file `example.js` line 103-124 
	(LOBBIES section with `createPracticeLobby` and `leavePracticeLobby`)
	- change `dota2.ServerRegion.PERFECTWORLDTELECOM` to `dota2.ServerRegion.STOCKHOLM`
4. first launch `node example.js`
	- result: `Connection closed by server: Error: Disconnected`
	- take guard code from email and put to `config.steamguard`
5. second launch
	- same result, copy from `example2.js` line:219
	`if (global.config.steam_guard_code) logOnDetails.auth_code = global.config.steam_guard_code;`
	to `example.js` after line 183
6. third launch
	- result is
```
15 Dec 22:02:40 - Logged on.
15 Dec 22:02:40 - Launching Dota 2
15 Dec 22:02:40 - Received servers.
15 Dec 22:02:41 - Sending ClientHello
15 Dec 22:02:42 - Received client welcome.
Node-dota2 ready.
15 Dec 22:02:42 - Sending match CMsgPracticeLobbyCreate request
15 Dec 22:02:42 - Cache(s) subscribed, type(s): 7
15 Dec 22:02:42 - Unhandled cache ID: 7
15 Dec 22:02:42 - Cache(s) subscribed, type(s): 2004
15 Dec 22:02:42 - Received lobby snapshot for lobby ID 24859523315999221
15 Dec 22:02:42 - Received create/flip/shuffle/kick/launch/leave response {"result":1}
{"result":1}
```
7. enter to lobby
	- open Dota2 game from another steam account
	- find my lobby `node-dota2` in lobbies list
	- enter to lobby when it was created, console result:
```
/var/www/node-dota2/node_modules/bytebuffer/dist/bytebuffer-node.js:346
throw TypeError("Illegal buffer");

TypeError: Illegal buffer
at Function.module.exports.ByteBuffer.wrap 
(/var/www/node-dota2/node_modules/bytebuffer/dist/bytebuffer-node.js:346:19)
at Function.Message.decode 
(/var/www/node-dota2/node_modules/protobufjs/dist/protobuf.js:2930:84)
at Dota2Client.handleSubscribedType (/var/www/node-dota2/handlers/cache.js:43:51)
at /var/www/node-dota2/handlers/cache.js:109:34
at Array.forEach (native)
at Dota2Client.onUpdateMultiple (/var/www/node-dota2/handlers/cache.js:108:32)
at SteamGameCoordinator.fromGC (/var/www/node-dota2/index.js:57:38)
at emitThree (events.js:116:13)
at SteamGameCoordinator.emit (events.js:194:7)
at SteamGameCoordinator.handlers.(anonymous function) 
(/var/www/node-dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:107:10)
```

try to run `update_proto.sh`, same result
my nodejs version is latest (`7.1.0`)

**Comment by Crazy-Duck** [comment]
Nice! I wish all bug reports were this detailed :laughing:  I'll look into it

**Comment by Crazy-Duck** [comment]
Staging & dev branches now contain the fix. I'll look into releasing a new version (4.2.0) this weekend/next week

**Comment by shockwaves** [comment]
great respect for your attention! =) its OK now)

**Comment by Crazy-Duck** [comment]
Nice to hear :)
