### ISSUE TITLE
addBotToPracticeLobby not working

### ISSUE THREAD

**Issue by notbdu** [Arcana/node-dota2#426]
I make this call after I create the lobby and invite myself to the lobby.

Code:
```
Dota2.addBotToPracticeLobby(
  1,
  dota2.schema.DOTA_GC_TEAM.GC_TEAM_GOOD_GUYS,
  dota2.schema.DOTABotDifficulty.BOT_DIFFICULTY_HARD,
  (err, resp) => {
    console.log(err);
    console.log(resp);
  }
);
```
Logs:
```
23 Jan 23:01:13 - Sending match CMsgPracticeLobbySetTeamSlot request
23 Jan 23:01:13 - Received create/flip/shuffle/kick/launch/leave response {"result":1}
```
My two console logs:
```
null
{ result: 1 }
```
I am in the lobby but I do not see any AI bots added.

**Comment by Crazy-Duck** [comment]
Protobufjs has changed their implementation. You need to explicitly resolve objects by type on the schema now. Try changing your code to
```
Dota2.addBotToPracticeLobby(
  1,
  dota2.schema.lookupEnum("DOTA_GC_TEAM").GC_TEAM_GOOD_GUYS,
  dota2.schema.lookupEnum("DOTABotDifficulty").BOT_DIFFICULTY_HARD,
  (err, resp) => {
    console.log(err);
    console.log(resp);
  }
);
```

**Comment by bdupharm** [comment]
It seems that I have `protobufjs@^5.0.0`.

The two enums resolve for me.
Logs: 
```
console.log(dota2.schema.DOTA_GC_TEAM.DOTA_GC_TEAM_GOOD_GUYS);
console.log(dota2.schema.DOTABotDifficulty.BOT_DIFFICULTY_HARD);
```
Out:
```
0
3
```

Trying:
```
Dota2.addBotToPracticeLobby(
  1,
  dota2.schema.lookupEnum("DOTA_GC_TEAM").GC_TEAM_GOOD_GUYS,
  dota2.schema.lookupEnum("DOTABotDifficulty").BOT_DIFFICULTY_HARD,
  (err, resp) => {
    console.log(err);
    console.log(resp);
  }
);
```
Out:
```
/Users/cd11/Documents/sandbox/dota2client/example.js:139
                      dota2.schema.lookupEnum('DOTA_GC_TEAM').DOTA_GC_TEAM_GOOD_GUYS,
                                   ^

TypeError: dota2.schema.lookupEnum is not a function
    at Timeout._onTimeout (/Users/cd11/Documents/sandbox/dota2client/example.js:139:36)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by bdupharm** [comment]
Still no luck adding an AI bot :(

**Comment by Crazy-Duck** [comment]
what version of the library are you using?

**Comment by bdupharm** [comment]
`dota2@4.1.0`

**Comment by devilesk** [comment]
I just tested addBotToPracticeLobby myself and it doesn't seem to be working. I'm just running a modified version of the example.js with the following in the ready callback:

```
Dota2.createPracticeLobby("password",
                        {"game_name": "nodedota2TEST",
                        "server_region": dota2.ServerRegion.USEAST,
                        "game_mode": dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_AP,
                        "series_type": 2,
                        "game_version": 1,
                        "allow_cheats": false,
                        "fill_with_bots": false,
                        "allow_spectating": true,
                        "pass_key": "password",
                        "radiant_series_wins": 0,
                        "dire_series_wins": 0,
                        "allchat": true
                        },
                        function(err, body){
                             console.log(JSON.stringify(body));
                             Dota2.addBotToPracticeLobby(7, dota2.schema.lookupEnum("DOTA_GC_TEAM").DOTA_GC_TEAM_BAD_GUYS, dota2.schema.lookupEnum("DOTABotDifficulty").BOT_DIFFICULTY_HARD, function (err, response) {
                                 console.log(JSON.stringify(response));
                             });
                        });
```

I think Valve might have just removed the functionality for adding individual bots to slots, because you can't even do it in the client anymore.

**Comment by Crazy-Duck** [comment]
if this is the case we're gonna have to put it deprecated then

**Comment by gerlaic** [comment]
I just tried to use the attributes in ```createPracticeLobby``` to try add bots into the game. You can set it with : ```"fill_with_bots": true```

However, other settings are not working such as:
```
"bot_difficulty_radiant": 2,
"bot_difficulty_dire": 3
```

And I didn't find any args to use custom bots

**Comment by Crazy-Duck** [comment]
@gerlaic the only lobby commands that are supported right now are: 
```
Dota2._lobbyOptions = {
    game_name: "string",
    server_region: "number",
    game_mode: "number",
    game_version: "number",
    cm_pick: "number",
    allow_cheats: "boolean",
    fill_with_bots: "boolean",
    allow_spectating: "boolean",
    pass_key: "string",
    series_type: "number",
    radiant_series_wins: "number",
    dire_series_wins: "number",
    allchat: "boolean",
    leagueid: "number",
    dota_tv_delay: "number",
    custom_game_mode: "string",
    custom_map_name: "string",
    custom_difficulty: "number",
    custom_game_id: "number",
};
```
Any other option that's passed to `createPracticeLobby` gets ignored. You'd need to create a PR where you add 
```
bot_difficulty_radiant: "number",
bot_difficulty_dire: "number",
bot_radiant: "number",
bot_dire: "number"
```
to the list of options, ask in #417 if they want to add it or wait for me to get around to doing it

**Comment by bdupharm** [comment]
Thanks for looking into this guys. 👍
