### ISSUE TITLE
connect api erro

### ISSUE THREAD

**Issue by thoitrangphovn** [Arcana/node-dota2#537]
Hi all, i have a problem
sometime I run ok, but somtime it's show error:
12 Sep 12:44:32 - Logged on.
2 September 12:44:32 - Launching Dota 2
12 Sep 12:44:32 - Received servers.
12 Sep 12:44:33 - Logged off from Steam.
Error: Disconnected
    at SteamClient._disconnected (/........../esport/node-dota2/node_modules/steam/lib/steam_client.js:186:24)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
12 Sep 12:44:33 - Connection closed by server.
2 September 12:44:33 - Sending ClientHello
/........./node-dota2/node_modules/steam/lib/steam_client.js:114
  this._connection.send(Buffer.concat([header.toBuffer(), body]));
                  ^

TypeError: Cannot read property 'send' of undefined
    at SteamClient._send (/.........../node_modules/steam/lib/steam_client.js:114:19)
    at SteamClient.send (/Users/os/www/ted/esport/node-dota2/node_modules/steam/lib/steam_client.js:123:8)
    at SteamGameCoordinator._send (/........./node-dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:49:16)
    at SteamGameCoordinator.send (/........./node-dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:67:8)
    at Timeout.Dota2Client._sendClientHello [as _onTimeout] (/.........../node-dota2/index.js:201:22)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

How to fix it? 
many thanks

**Comment by Crazy-Duck** [comment]
Could you provide a bit more detail on what it is exactly that you're doing? Like a code sample or something

**Comment by Crazy-Duck** [comment]
Stale

**Comment by sborod** [comment]
I have the same error output today. But fix founded. It appears when second dota 2 client started with the same credentials.
