### ISSUE TITLE
new. Dota2.Client Debug error

### ISSUE THREAD

**Issue by LucidEnch** [Arcana/node-dota2#587]
Dota2 = new dota2.Dota2Client(steamClient,debug, debugMore);
                                              ^

ReferenceError: debug is not defined
    at Object.<anonymous> (C:\nodejs\node_modules\npm\node_modules\node-dota2\examples\dota2.js:9:47)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)

**Comment by qing5hu1** [comment]
The debug param is a boolean so it should be either true or false.
Correct usage is:
`Dota2 = new dota2.Dota2Client(steamClient, true, true);`

**Comment by LucidEnch** [comment]
I tried to use an example and set: new dota2.Dota2Client(steamClient, true, true); but I can't write something on cmd after receiving a Client Welcome from GC. I guess that I can communicate directly with GC, without presets in .is file
