### ISSUE TITLE
Error: Expecting terminator

### ISSUE THREAD

**Issue by matheuschagas** [Arcana/node-dota2#593]
When I run example.js i got this error:
```
/usr/local/bin/node /home/matheusmarrane/WebstormProjects/wisercupbot/examples/example.js
/home/matheusmarrane/WebstormProjects/wisercupbot/node_modules/steam/node_modules/steam-resources/steam_language_parser/parser/token_analyzer.js:188
    throw new Error("Expecting " + name);
    ^

Error: Expecting terminator
    at expect (/home/matheusmarrane/WebstormProjects/wisercupbot/node_modules/steam/node_modules/steam-resources/steam_language_parser/parser/token_analyzer.js:188:11)
    at parseInnerScope (/home/matheusmarrane/WebstormProjects/wisercupbot/node_modules/steam/node_modules/steam-resources/steam_language_parser/parser/token_analyzer.js:161:7)
    at Object.exports.analyze (/home/matheusmarrane/WebstormProjects/wisercupbot/node_modules/steam/node_modules/steam-resources/steam_language_parser/parser/token_analyzer.js:103:15)
    at Object.exports.analyze (/home/matheusmarrane/WebstormProjects/wisercupbot/node_modules/steam/node_modules/steam-resources/steam_language_parser/parser/token_analyzer.js:36:33)
    at Object.exports.analyze (/home/matheusmarrane/WebstormProjects/wisercupbot/node_modules/steam/node_modules/steam-resources/steam_language_parser/parser/token_analyzer.js:36:33)
    at Object.<anonymous> (/home/matheusmarrane/WebstormProjects/wisercupbot/node_modules/steam/node_modules/steam-resources/steam_language_parser/index.js:12:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

Process finished with exit code 1

```

I'm using linux
Node: v8.11.1
npm: 5.6.0

**Comment by matheuschagas** [comment]
I saw their docs and they recommend us to install node-steam directly from npm, and for me it works

**Comment by essramos** [comment]
@matheuschagas can you show you resolved this issue? I am having the same one, I run npm install inside the steam-resources directory already.

**Comment by matheuschagas** [comment]
I don't remember, but I guess this error is related to a specific node version
