### ISSUE TITLE
Running example.js issue

### ISSUE THREAD

**Issue by essramos** [Arcana/node-dota2#599]
I followed the instructions on the readme.md and now I am trying to execute example.js from the examples folder. I am getting the error below. 

```
C:\Users\user\Desktop\test\node-dota2\node_modules\steam\node_modules\st
eam-resources\steam_language_parser\index.js:10
process.chdir(languagePath);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Object.<anonymous> (C:\Users\user\Desktop\test\node-dota2\node_mo
dules\steam\node_modules\steam-resources\steam_language_parser\index.js:10:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\Desktop\test\node-dota2\node_mo
dules\steam\node_modules\steam-resources\index.js:81:1)
    at Module._compile (module.js:652:30)

```
I looked at the steam folder and which js file was causing the issue.  
Line 10 is causing the error it is looking for this file or folder. im not sure. Should I be creating this file? 

```
C:\Users\user\Desktop\test\node-dota2\node_modules\steam\node
_modules\steam-resources\steam_language
```

![image](https://user-images.githubusercontent.com/8519223/43111525-46827bc8-8f24-11e8-9c08-289e16a23179.png)

**NPM version: 5.6.0**
**Node.js version : v8.11.1**

**Comment by essramos** [comment]
I resolved the issue by running `npm install` inside the `node-modules > steam > steam_resources`
