### ISSUE TITLE
no such Enum 'EGCSystemMsg' in Root (node-dota2 installation)

### ISSUE THREAD

**Issue by csplkiller** [Arcana/node-dota2#631]
Help with installing node-dota2

I used node-dota2 long enough until it stopped working.
I decided to install node-dota2 the latest version from the very beginning, but I ran into difficulties.
I hope local specialists will be able to help me.

How do I install node-dota2. Please point me to my errors.

**wget https://github.com/Arcana/node-dota2/archive/staging.zip**
**unzip staging.zip**

**npm install**

**cd /scripts/dota2/node_modules/protobufjs**
**node scripts/postinstall**

**cd /scripts/dota2/node_modules/steam**
**npm install**

**su -c "npm install seishun/node-steam-resources" user**

**cd /scripts/dota2/node_modules/steam/node_modules/steam-resources**
**npm install**
At this moment I have some kind of conflicts, the cause of which I do not know, I press "r" to complete the script.

`  C protobufs/LICENSE
   C protobufs/README.md
   C protobufs/artifact
   A protobufs/artifact/base_gcmessages.proto
   A protobufs/artifact/c_peer2peer_netmessages.proto
   A protobufs/artifact/clientmessages.proto
   A protobufs/artifact/connectionless_netmessages.proto
   ......
Select: (r) mark resolved, (p) postpone, (q) quit resolution, (h) help: r
Resolved conflicted state of 'protobufs/.gitattributes'
Tree conflict on 'protobufs/LICENSE'
   ......`

After i run update_proto.sh

**./update_proto.sh**

After creating my config.js, I try to run the program ... but I get an error!

**cd /scripts/dota2/examples**

`root@user:/scripts/dota2/examples# su -c "node example.js" user
29 Dec 02:24:54 - Cannae load the sentry. Error: ENOENT: no such file or directory, open 'sentry'
29 Dec 02:24:55 - Logged on.
29 Dec 02:24:55 - Launching Dota 2
29 Dec 02:24:55 - Received servers.
29 Dec 02:24:56 - Sending ClientHello
29 Dec 02:25:01 - Sending ClientHello
/scripts/dota2/node_modules/protobufjs/src/namespace.js:396
        throw Error("no such Enum '" + path + "' in " + this);
        ^

Error: no such Enum 'EGCSystemMsg' in Root
    at Root.lookupEnum (/scripts/dota2/node_modules/protobufjs/src/namespace.js:396:15)
    at Object.Dota2._getMessageName (/scripts/dota2/handlers/helper.js:192:34)
    at SteamGameCoordinator.fromGC (/scripts/dota2/index.js:166:52)
    at emitThree (events.js:135:13)
    at SteamGameCoordinator.emit (events.js:216:7)
    at SteamGameCoordinator.handlers.(anonymous function) (/scripts/dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:107:10)
    at SteamGameCoordinator.<anonymous> (/scripts/dota2/node_modules/steam/lib/handlers/game_coordinator/index.js:19:28)
    at emitThree (events.js:140:20)
    at SteamClient.emit (events.js:216:7)
    at SteamClient._netMsgReceived (/scripts/dota2/node_modules/steam/lib/steam_client.js:172:10)
root@user:/scripts/dota2/examples#
`

What have I done wrong ?

**Comment by csplkiller** [comment]
If you copy the old /proto files
then the program starts working without errors.

Then the question arises. And how to update the proto files now?
