### ISSUE TITLE
it's chat bug

### ISSUE THREAD

**Issue by Batterfly** [Arcana/node-dota2#668]
when i send message to channel，and will throw this error ;
joinChat->sendMessage->leaveChat

C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\dota2\handlers\chat.js:22
            return (item.channel_id.equals(channel_id));
                                    ^

TypeError: Cannot read property 'equals' of null
    at C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\dota2\handlers\chat.js:22:37
    at Array.filter (<anonymous>)
    at Dota2Client.Dota2.Dota2Client._getChannelById (C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\dota2\handlers\chat.js:19:30)
    at Dota2Client.onChatMessage (C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\dota2\handlers\chat.js:258:24)
    at SteamGameCoordinator.fromGC (C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\dota2\index.js:172:38)
    at SteamGameCoordinator.emit (events.js:189:13)
    at SteamGameCoordinator.handlers.(anonymous function) (C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\steam\lib\handlers\game_coordinator\index.js:107:10)
    at SteamGameCoordinator.<anonymous> (C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\steam\lib\handlers\game_coordinator\index.js:19:28)
    at SteamClient.emit (events.js:194:15)
    at SteamClient._netMsgReceived (C:\Users\Justine\WebstormProjects\dota2Bot\node_modules\steam\lib\steam_client.js:175:10)

**Comment by metrogit** [comment]
i have the same err here did you fix it ? pls help me
