### ISSUE TITLE
Can't run example.js

### ISSUE THREAD

**Issue by worldofsites** [Arcana/node-dota2#676]
Hi there!

After running `node example.js` got the following results:
```
~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:1530
                    throw Error("Duplicate name in namespace "+this.toString(true)+": "+child.name);
                    ^

Error: Duplicate name in namespace Namespace : CExtraMsgBlock
    at Namespace.ProtoBuf.Reflect.NamespacePrototype.addChild (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:1530:27)
    at Builder.ProtoBuf.Builder.BuilderPrototype.create (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:4470:34)
    at Builder.ProtoBuf.Builder.BuilderPrototype.import (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:4669:22)
    at Object.ProtoBuf.loadJson (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:5135:26)
    at Object.ProtoBuf.loadProto (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:5038:25)
    at Object.ProtoBuf.loadProtoFile (~\node-worker\node_modules\protobufjs\dist\ProtoBuf.js:5084:52)
    at ~\node-worker\node_modules\steam-resources\index.js:41:14
    at Array.forEach (<anonymous>)
    at loadProtoFiles (~\node-worker\node_modules\steam-resources\index.js:40:9)
    at Object.<anonymous> (~\node-worker\node_modules\steam-resources\index.js:33:15)
```

**Comment by worldofsites** [comment]
Created also ticket in `node-steam-resources` https://github.com/seishun/node-steam-resources/issues/7
